"""Provider- and backend-neutral Threadline Factory registry boundary."""

from .models import (
    DispatchSnapshot,
    Evidence,
    FailureCode,
    Feature,
    Lane,
    Lease,
    PackageKind,
    TaskStatus,
    Worker,
    WorkPackage,
)
from .repository import Registry, RegistryConflict, RegistryError, RegistryNotFound
from .shadow_dispatch import (
    Assignment,
    DifferenceClassification,
    LegacyComparison,
    LegacyObservation,
    OutcomeSimulationEvidence,
    RejectionCode,
    ShadowDecision,
    ShadowDispatchError,
    ShadowHarnessEvidence,
    ShadowPolicy,
    compare_with_legacy,
    decide_shadow,
    run_required_shadow_harness,
    simulate_outcome,
    snapshot_fingerprint,
    write_shadow_harness_evidence,
)
from .sqlite_registry import SQLiteRegistry

__all__ = [
    "Evidence",
    "Assignment",
    "DifferenceClassification",
    "DispatchSnapshot",
    "FailureCode",
    "Feature",
    "Lane",
    "LegacyComparison",
    "LegacyObservation",
    "OutcomeSimulationEvidence",
    "Lease",
    "PackageKind",
    "Registry",
    "RegistryConflict",
    "RegistryError",
    "RegistryNotFound",
    "RejectionCode",
    "SQLiteRegistry",
    "TaskStatus",
    "ShadowDecision",
    "ShadowDispatchError",
    "ShadowHarnessEvidence",
    "ShadowPolicy",
    "Worker",
    "WorkPackage",
    "compare_with_legacy",
    "decide_shadow",
    "run_required_shadow_harness",
    "simulate_outcome",
    "snapshot_fingerprint",
    "write_shadow_harness_evidence",
]
